### PR TITLE
Added find method that allows filtering by regular expression.

### PR DESCRIPTION
**Pull request by dekobon**
I created a function that allows for mfind style filename searches from Manta. I use a similar method all of the time in my project. I would like to see this in the library.

Tests are missing from this repository because I have no idea how to hook up to the test Manta instance that Joyent is using internally to run tests against. Please advise.

### CODE REVIEW

**Comment by davepacheco** [comment]
Can you run the tests against our production Manta deployment?

**Comment by Marsell** [comment]
Yes, the tests run just fine against the production Manta deployment.

E.g. this runs it for me (from the tests/ dir):

USER=marsell KEY=~/.ssh/joyent HOST=https://us-east.manta.joyent.com ruby test_ruby-manta.rb

Substitute USER and KEY as fits your case.

**Comment by dekobon** [comment]
@davepacheco I'm finishing up my changes to the ruby-manta gem. After I work through
tests and some permissions errors, we should be able to cut a new gem.
Could you track down who has permissions to push to ruby gems?

**Comment by davepacheco** [comment]
@marsell, do you know about the permissions?

**Comment by Marsell** [comment]
@dap, I can do that.

@dekobon, I'm a concerned about the commit adding RubyManta::MantaClient, due to backwards compatibility. I rather we don't break existing code unless there's a very good reason for it.

**Comment by dekobon** [comment]
I'm happy to revert the change, but I did use semantic versioning to
indicate that it is a breaking change. Bundler won't auto update peoples
projects if they used the proper version identifier.

The rational behind the breaking change was that the entire module is done
in a  unconventional way. And conventions are really important in the ruby
community. My goal was to bring it back to a conventional approach.

One thing I can do is use ruby features in order to preserve the API and
output deprecation messages.

By the way thanks for reading through the changes, I was really hoping for
some input.

**Comment by Marsell** [comment]
Since the rest of the api hasn't had breaking changes, is it possible to expose both MantaClient and RubyManta::MantaClient? Use RubyManta::MantaClient in the example and README, but provide MantaClient as legacy.

**Comment by dekobon** [comment]
Yup, that's exactly what I was thinking. What do you think about throwing a
warning if it is accessed in that way?

**Comment by Marsell** [comment]
You mean like 'warn "foo"'?

Ambivalent. I can see the merit of it, but maybe a more gradual process is in order.

You could put a note in the docs that using MantaClient is deprecated, and in a few months we can add the warnings, then after a year chop MantaClient out.

I'll leave this as your call.

**Comment by dekobon** [comment]
Yeah, I decided to omit the warning because it would be too much work
creating a wrapper where it would be invoked. It should now be API
compatible with 1.x.x.

On Fri, Mar 13, 2015 at 7:48 PM, Marsell <notifications@github.com> wrote:

> You mean like 'warn "foo"'?
>
> Ambivalent. I can see the merit of it, but maybe a more gradual process is
> in order.
>
> You could put a note in the docs that using MantaClient is deprecated, and
> in a few months we can add the warnings, then after a year chop MantaClient
> out.
>
> I'll leave this as your call.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joyent/ruby-manta/pull/9#issuecomment-79739254>.
>



-- 
-Elijah

**Comment by Marsell** [comment]
Thanks so much for working on this. :)

I've pushed the 2.0.0 gem to rubygems. Please let me know if everything works properly when you install it.

**Pull request merged**
